package net.pedroricardo.headed.block;

import net.minecraft.block.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import net.pedroricardo.headed.Headed;

public class HeadedBlocks {
    public static final Block VILLAGER_HEAD;
    public static final Block VILLAGER_WALL_HEAD;
    public static final Block EVOKER_HEAD;
    public static final Block EVOKER_WALL_HEAD;
    public static final Block VINDICATOR_HEAD;
    public static final Block VINDICATOR_WALL_HEAD;
    public static final Block PILLAGER_HEAD;
    public static final Block PILLAGER_WALL_HEAD;
    public static final Block ZOMBIE_VILLAGER_HEAD;
    public static final Block ZOMBIE_VILLAGER_WALL_HEAD;
    public static final Block ILLUSIONER_HEAD;
    public static final Block ILLUSIONER_WALL_HEAD;
    public static final Block SHEEP_HEAD;
    public static final Block SHEEP_WALL_HEAD;
    public static final Block WHITE_SHEEP_HEAD;
    public static final Block WHITE_SHEEP_WALL_HEAD;
    public static final Block ORANGE_SHEEP_HEAD;
    public static final Block ORANGE_SHEEP_WALL_HEAD;
    public static final Block MAGENTA_SHEEP_HEAD;
    public static final Block MAGENTA_SHEEP_WALL_HEAD;
    public static final Block LIGHT_BLUE_SHEEP_HEAD;
    public static final Block LIGHT_BLUE_SHEEP_WALL_HEAD;
    public static final Block YELLOW_SHEEP_HEAD;
    public static final Block YELLOW_SHEEP_WALL_HEAD;
    public static final Block LIME_SHEEP_HEAD;
    public static final Block LIME_SHEEP_WALL_HEAD;
    public static final Block PINK_SHEEP_HEAD;
    public static final Block PINK_SHEEP_WALL_HEAD;
    public static final Block GRAY_SHEEP_HEAD;
    public static final Block GRAY_SHEEP_WALL_HEAD;
    public static final Block LIGHT_GRAY_SHEEP_HEAD;
    public static final Block LIGHT_GRAY_SHEEP_WALL_HEAD;
    public static final Block CYAN_SHEEP_HEAD;
    public static final Block CYAN_SHEEP_WALL_HEAD;
    public static final Block PURPLE_SHEEP_HEAD;
    public static final Block PURPLE_SHEEP_WALL_HEAD;
    public static final Block BLUE_SHEEP_HEAD;
    public static final Block BLUE_SHEEP_WALL_HEAD;
    public static final Block BROWN_SHEEP_HEAD;
    public static final Block BROWN_SHEEP_WALL_HEAD;
    public static final Block GREEN_SHEEP_HEAD;
    public static final Block GREEN_SHEEP_WALL_HEAD;
    public static final Block RED_SHEEP_HEAD;
    public static final Block RED_SHEEP_WALL_HEAD;
    public static final Block BLACK_SHEEP_HEAD;
    public static final Block BLACK_SHEEP_WALL_HEAD;
    public static final Block ALLAY_HEAD;
    public static final Block ALLAY_WALL_HEAD;
    public static final Block VEX_HEAD;
    public static final Block VEX_WALL_HEAD;
    public static final Block PIGLIN_BRUTE_HEAD;
    public static final Block PIGLIN_BRUTE_WALL_HEAD;
    public static final Block ZOMBIFIED_PIGLIN_HEAD;
    public static final Block ZOMBIFIED_PIGLIN_WALL_HEAD;
    public static final Block LEUCISTIC_AXOLOTL_HEAD;
    public static final Block LEUCISTIC_AXOLOTL_WALL_HEAD;
    public static final Block BROWN_AXOLOTL_HEAD;
    public static final Block BROWN_AXOLOTL_WALL_HEAD;
    public static final Block CYAN_AXOLOTL_HEAD;
    public static final Block CYAN_AXOLOTL_WALL_HEAD;
    public static final Block GOLD_AXOLOTL_HEAD;
    public static final Block GOLD_AXOLOTL_WALL_HEAD;
    public static final Block BLUE_AXOLOTL_HEAD;
    public static final Block BLUE_AXOLOTL_WALL_HEAD;
    public static final Block COW_HEAD;
    public static final Block COW_WALL_HEAD;
    public static final Block BROWN_MOOSHROOM_HEAD;
    public static final Block BROWN_MOOSHROOM_WALL_HEAD;
    public static final Block RED_MOOSHROOM_HEAD;
    public static final Block RED_MOOSHROOM_WALL_HEAD;
    public static final Block POLAR_BEAR_HEAD;
    public static final Block POLAR_BEAR_WALL_HEAD;
    public static final Block OCELOT_HEAD;
    public static final Block OCELOT_WALL_HEAD;
    public static final Block ALL_BLACK_CAT_HEAD;
    public static final Block ALL_BLACK_CAT_WALL_HEAD;
    public static final Block BLACK_CAT_HEAD;
    public static final Block BLACK_CAT_WALL_HEAD;
    public static final Block BRITISH_SHORTHAIR_CAT_HEAD;
    public static final Block BRITISH_SHORTHAIR_CAT_WALL_HEAD;
    public static final Block CALICO_CAT_HEAD;
    public static final Block CALICO_CAT_WALL_HEAD;
    public static final Block JELLIE_CAT_HEAD;
    public static final Block JELLIE_CAT_WALL_HEAD;
    public static final Block PERSIAN_CAT_HEAD;
    public static final Block PERSIAN_CAT_WALL_HEAD;
    public static final Block RAGDOLL_CAT_HEAD;
    public static final Block RAGDOLL_CAT_WALL_HEAD;
    public static final Block RED_CAT_HEAD;
    public static final Block RED_CAT_WALL_HEAD;
    public static final Block SIAMESE_CAT_HEAD;
    public static final Block SIAMESE_CAT_WALL_HEAD;
    public static final Block TABBY_CAT_HEAD;
    public static final Block TABBY_CAT_WALL_HEAD;
    public static final Block WHITE_CAT_HEAD;
    public static final Block WHITE_CAT_WALL_HEAD;
    public static final Block ENDERMAN_HEAD;
    public static final Block ENDERMAN_WALL_HEAD;


    static {
        VILLAGER_HEAD = register("villager_head", new HeadedSkullBlock(HeadedSkullBlock.Type.VILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        VILLAGER_WALL_HEAD = register("villager_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.VILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(VILLAGER_HEAD)));
        EVOKER_HEAD = register("evoker_head", new HeadedSkullBlock(HeadedSkullBlock.Type.EVOKER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        EVOKER_WALL_HEAD = register("evoker_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.EVOKER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(EVOKER_HEAD)));
        VINDICATOR_HEAD = register("vindicator_head", new HeadedSkullBlock(HeadedSkullBlock.Type.VINDICATOR, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        VINDICATOR_WALL_HEAD = register("vindicator_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.VINDICATOR, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(VINDICATOR_HEAD)));
        PILLAGER_HEAD = register("pillager_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PILLAGER_WALL_HEAD = register("pillager_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PILLAGER_HEAD)));
        ZOMBIE_VILLAGER_HEAD = register("zombie_villager_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ZOMBIE_VILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ZOMBIE_VILLAGER_WALL_HEAD = register("zombie_villager_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ZOMBIE_VILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ZOMBIE_VILLAGER_HEAD)));
        SHEEP_HEAD = register("sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        SHEEP_WALL_HEAD = register("sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(SHEEP_HEAD)));
        WHITE_SHEEP_HEAD = register("white_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WHITE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WHITE_SHEEP_WALL_HEAD = register("white_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WHITE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WHITE_SHEEP_HEAD)));
        ORANGE_SHEEP_HEAD = register("orange_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ORANGE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ORANGE_SHEEP_WALL_HEAD = register("orange_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ORANGE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ORANGE_SHEEP_HEAD)));
        MAGENTA_SHEEP_HEAD = register("magenta_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.MAGENTA_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        MAGENTA_SHEEP_WALL_HEAD = register("magenta_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.MAGENTA_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(MAGENTA_SHEEP_HEAD)));
        LIGHT_BLUE_SHEEP_HEAD = register("light_blue_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.LIGHT_BLUE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        LIGHT_BLUE_SHEEP_WALL_HEAD = register("light_blue_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.LIGHT_BLUE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(LIGHT_BLUE_SHEEP_HEAD)));
        YELLOW_SHEEP_HEAD = register("yellow_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.YELLOW_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        YELLOW_SHEEP_WALL_HEAD = register("yellow_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.YELLOW_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(YELLOW_SHEEP_HEAD)));
        LIME_SHEEP_HEAD = register("lime_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.LIME_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        LIME_SHEEP_WALL_HEAD = register("lime_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.LIME_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(LIME_SHEEP_HEAD)));
        PINK_SHEEP_HEAD = register("pink_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PINK_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PINK_SHEEP_WALL_HEAD = register("pink_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PINK_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PINK_SHEEP_HEAD)));
        GRAY_SHEEP_HEAD = register("gray_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.GRAY_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        GRAY_SHEEP_WALL_HEAD = register("gray_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.GRAY_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(GRAY_SHEEP_HEAD)));
        LIGHT_GRAY_SHEEP_HEAD = register("light_gray_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.LIGHT_GRAY_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        LIGHT_GRAY_SHEEP_WALL_HEAD = register("light_gray_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.LIGHT_GRAY_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(LIGHT_GRAY_SHEEP_HEAD)));
        CYAN_SHEEP_HEAD = register("cyan_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.CYAN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        CYAN_SHEEP_WALL_HEAD = register("cyan_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.CYAN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(CYAN_SHEEP_HEAD)));
        PURPLE_SHEEP_HEAD = register("purple_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PURPLE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PURPLE_SHEEP_WALL_HEAD = register("purple_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PURPLE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PURPLE_SHEEP_HEAD)));
        BLUE_SHEEP_HEAD = register("blue_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLUE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLUE_SHEEP_WALL_HEAD = register("blue_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLUE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLUE_SHEEP_HEAD)));
        BROWN_SHEEP_HEAD = register("brown_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BROWN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BROWN_SHEEP_WALL_HEAD = register("brown_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BROWN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BROWN_SHEEP_HEAD)));
        GREEN_SHEEP_HEAD = register("green_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.GREEN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        GREEN_SHEEP_WALL_HEAD = register("green_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.GREEN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(GREEN_SHEEP_HEAD)));
        RED_SHEEP_HEAD = register("red_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.RED_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        RED_SHEEP_WALL_HEAD = register("red_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.RED_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(RED_SHEEP_HEAD)));
        BLACK_SHEEP_HEAD = register("black_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLACK_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLACK_SHEEP_WALL_HEAD = register("black_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLACK_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLACK_SHEEP_HEAD)));
        ALLAY_HEAD = register("allay_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ALLAY, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).luminance(state -> 15)));
        ALLAY_WALL_HEAD = register("allay_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ALLAY, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).luminance(state -> 15).dropsLike(ALLAY_HEAD)));
        VEX_HEAD = register("vex_head", new HeadedSkullBlock(HeadedSkullBlock.Type.VEX, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        VEX_WALL_HEAD = register("vex_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.VEX, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(VEX_HEAD)));
        ILLUSIONER_HEAD = register("illusioner_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ILLUSIONER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ILLUSIONER_WALL_HEAD = register("illusioner_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ILLUSIONER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ILLUSIONER_HEAD)));
        PIGLIN_BRUTE_HEAD = register("piglin_brute_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PIGLIN_BRUTE, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PIGLIN_BRUTE_WALL_HEAD = register("piglin_brute_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PIGLIN_BRUTE, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PIGLIN_BRUTE_HEAD)));
        ZOMBIFIED_PIGLIN_HEAD = register("zombified_piglin_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ZOMBIFIED_PIGLIN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ZOMBIFIED_PIGLIN_WALL_HEAD = register("zombified_piglin_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ZOMBIFIED_PIGLIN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ZOMBIFIED_PIGLIN_HEAD)));
        LEUCISTIC_AXOLOTL_HEAD = register("leucistic_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.LEUCISTIC_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        LEUCISTIC_AXOLOTL_WALL_HEAD = register("leucistic_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.LEUCISTIC_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(LEUCISTIC_AXOLOTL_HEAD)));
        BROWN_AXOLOTL_HEAD = register("brown_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BROWN_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BROWN_AXOLOTL_WALL_HEAD = register("brown_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BROWN_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BROWN_AXOLOTL_HEAD)));
        CYAN_AXOLOTL_HEAD = register("cyan_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.CYAN_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        CYAN_AXOLOTL_WALL_HEAD = register("cyan_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.CYAN_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(CYAN_AXOLOTL_HEAD)));
        GOLD_AXOLOTL_HEAD = register("gold_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.GOLD_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        GOLD_AXOLOTL_WALL_HEAD = register("gold_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.GOLD_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(GOLD_AXOLOTL_HEAD)));
        BLUE_AXOLOTL_HEAD = register("blue_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLUE_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLUE_AXOLOTL_WALL_HEAD = register("blue_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLUE_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLUE_AXOLOTL_HEAD)));
        COW_HEAD = register("cow_head", new HeadedSkullBlock(HeadedSkullBlock.Type.COW, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        COW_WALL_HEAD = register("cow_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.COW, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(COW_HEAD)));
        BROWN_MOOSHROOM_HEAD = register("brown_mooshroom_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BROWN_MOOSHROOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BROWN_MOOSHROOM_WALL_HEAD = register("brown_mooshroom_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BROWN_MOOSHROOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BROWN_MOOSHROOM_HEAD)));
        RED_MOOSHROOM_HEAD = register("red_mooshroom_head", new HeadedSkullBlock(HeadedSkullBlock.Type.RED_MOOSHROOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        RED_MOOSHROOM_WALL_HEAD = register("red_mooshroom_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.RED_MOOSHROOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(RED_MOOSHROOM_HEAD)));
        POLAR_BEAR_HEAD = register("polar_bear_head", new HeadedSkullBlock(HeadedSkullBlock.Type.POLAR_BEAR, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        POLAR_BEAR_WALL_HEAD = register("polar_bear_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.POLAR_BEAR, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(POLAR_BEAR_HEAD)));
        OCELOT_HEAD = register("ocelot_head", new HeadedSkullBlock(HeadedSkullBlock.Type.OCELOT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        OCELOT_WALL_HEAD = register("ocelot_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.OCELOT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(OCELOT_HEAD)));
        ALL_BLACK_CAT_HEAD = register("all_black_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ALL_BLACK_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ALL_BLACK_CAT_WALL_HEAD = register("all_black_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ALL_BLACK_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ALL_BLACK_CAT_HEAD)));
        BLACK_CAT_HEAD = register("black_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLACK_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLACK_CAT_WALL_HEAD = register("black_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLACK_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLACK_CAT_HEAD)));
        BRITISH_SHORTHAIR_CAT_HEAD = register("british_shorthair_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BRITISH_SHORTHAIR_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BRITISH_SHORTHAIR_CAT_WALL_HEAD = register("british_shorthair_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BRITISH_SHORTHAIR_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BRITISH_SHORTHAIR_CAT_HEAD)));
        CALICO_CAT_HEAD = register("calico_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.CALICO_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        CALICO_CAT_WALL_HEAD = register("calico_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.CALICO_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(CALICO_CAT_HEAD)));
        JELLIE_CAT_HEAD = register("jellie_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.JELLIE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        JELLIE_CAT_WALL_HEAD = register("jellie_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.JELLIE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(JELLIE_CAT_HEAD)));
        PERSIAN_CAT_HEAD = register("persian_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PERSIAN_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PERSIAN_CAT_WALL_HEAD = register("persian_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PERSIAN_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PERSIAN_CAT_HEAD)));
        RAGDOLL_CAT_HEAD = register("ragdoll_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.RAGDOLL_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        RAGDOLL_CAT_WALL_HEAD = register("ragdoll_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.RAGDOLL_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(RAGDOLL_CAT_HEAD)));
        RED_CAT_HEAD = register("red_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.RED_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        RED_CAT_WALL_HEAD = register("red_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.RED_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(RED_CAT_HEAD)));
        SIAMESE_CAT_HEAD = register("siamese_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.SIAMESE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        SIAMESE_CAT_WALL_HEAD = register("siamese_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.SIAMESE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(SIAMESE_CAT_HEAD)));
        TABBY_CAT_HEAD = register("tabby_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.TABBY_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        TABBY_CAT_WALL_HEAD = register("tabby_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.TABBY_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(TABBY_CAT_HEAD)));
        WHITE_CAT_HEAD = register("white_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WHITE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WHITE_CAT_WALL_HEAD = register("white_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WHITE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WHITE_CAT_HEAD)));
        ENDERMAN_HEAD = register("enderman_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ENDERMAN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ENDERMAN_WALL_HEAD = register("enderman_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ENDERMAN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ENDERMAN_HEAD)));
    }

    private static Block register(String name, Block block) {
        return Registry.register(Registries.BLOCK, new Identifier(Headed.MOD_ID, name), block);
    }

    public static void registerModBlocks() {
        Headed.LOGGER.debug("Registering Headed blocks");
    }
}
