package net.pedroricardo.headed.block;

import net.minecraft.block.*;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import net.pedroricardo.headed.Headed;

public class HeadedBlocks {
    
    public static final Block VILLAGER_HEAD;
    public static final Block VILLAGER_WALL_HEAD;
    public static final Block EVOKER_HEAD;
    public static final Block EVOKER_WALL_HEAD;
    public static final Block VINDICATOR_HEAD;
    public static final Block VINDICATOR_WALL_HEAD;
    public static final Block PILLAGER_HEAD;
    public static final Block PILLAGER_WALL_HEAD;
    public static final Block ZOMBIE_VILLAGER_HEAD;
    public static final Block ZOMBIE_VILLAGER_WALL_HEAD;
    public static final Block WANDERING_TRADER_HEAD;
    public static final Block WANDERING_TRADER_WALL_HEAD;
    public static final Block ILLUSIONER_HEAD;
    public static final Block ILLUSIONER_WALL_HEAD;
    public static final Block SHEEP_HEAD;
    public static final Block SHEEP_WALL_HEAD;
    public static final Block WHITE_SHEEP_HEAD;
    public static final Block WHITE_SHEEP_WALL_HEAD;
    public static final Block ORANGE_SHEEP_HEAD;
    public static final Block ORANGE_SHEEP_WALL_HEAD;
    public static final Block MAGENTA_SHEEP_HEAD;
    public static final Block MAGENTA_SHEEP_WALL_HEAD;
    public static final Block LIGHT_BLUE_SHEEP_HEAD;
    public static final Block LIGHT_BLUE_SHEEP_WALL_HEAD;
    public static final Block YELLOW_SHEEP_HEAD;
    public static final Block YELLOW_SHEEP_WALL_HEAD;
    public static final Block LIME_SHEEP_HEAD;
    public static final Block LIME_SHEEP_WALL_HEAD;
    public static final Block PINK_SHEEP_HEAD;
    public static final Block PINK_SHEEP_WALL_HEAD;
    public static final Block GRAY_SHEEP_HEAD;
    public static final Block GRAY_SHEEP_WALL_HEAD;
    public static final Block LIGHT_GRAY_SHEEP_HEAD;
    public static final Block LIGHT_GRAY_SHEEP_WALL_HEAD;
    public static final Block CYAN_SHEEP_HEAD;
    public static final Block CYAN_SHEEP_WALL_HEAD;
    public static final Block PURPLE_SHEEP_HEAD;
    public static final Block PURPLE_SHEEP_WALL_HEAD;
    public static final Block BLUE_SHEEP_HEAD;
    public static final Block BLUE_SHEEP_WALL_HEAD;
    public static final Block BROWN_SHEEP_HEAD;
    public static final Block BROWN_SHEEP_WALL_HEAD;
    public static final Block GREEN_SHEEP_HEAD;
    public static final Block GREEN_SHEEP_WALL_HEAD;
    public static final Block RED_SHEEP_HEAD;
    public static final Block RED_SHEEP_WALL_HEAD;
    public static final Block BLACK_SHEEP_HEAD;
    public static final Block BLACK_SHEEP_WALL_HEAD;
    public static final Block ALLAY_HEAD;
    public static final Block ALLAY_WALL_HEAD;
    public static final Block VEX_HEAD;
    public static final Block VEX_WALL_HEAD;
    public static final Block PIGLIN_HEAD;
    public static final Block PIGLIN_WALL_HEAD;
    public static final Block PIGLIN_BRUTE_HEAD;
    public static final Block PIGLIN_BRUTE_WALL_HEAD;
    public static final Block ZOMBIFIED_PIGLIN_HEAD;
    public static final Block ZOMBIFIED_PIGLIN_WALL_HEAD;
    public static final Block LEUCISTIC_AXOLOTL_HEAD;
    public static final Block LEUCISTIC_AXOLOTL_WALL_HEAD;
    public static final Block BROWN_AXOLOTL_HEAD;
    public static final Block BROWN_AXOLOTL_WALL_HEAD;
    public static final Block CYAN_AXOLOTL_HEAD;
    public static final Block CYAN_AXOLOTL_WALL_HEAD;
    public static final Block GOLD_AXOLOTL_HEAD;
    public static final Block GOLD_AXOLOTL_WALL_HEAD;
    public static final Block BLUE_AXOLOTL_HEAD;
    public static final Block BLUE_AXOLOTL_WALL_HEAD;
    public static final Block COW_HEAD;
    public static final Block COW_WALL_HEAD;
    public static final Block BROWN_MOOSHROOM_HEAD;
    public static final Block BROWN_MOOSHROOM_WALL_HEAD;
    public static final Block RED_MOOSHROOM_HEAD;
    public static final Block RED_MOOSHROOM_WALL_HEAD;
    public static final Block POLAR_BEAR_HEAD;
    public static final Block POLAR_BEAR_WALL_HEAD;
    public static final Block OCELOT_HEAD;
    public static final Block OCELOT_WALL_HEAD;
    public static final Block ALL_BLACK_CAT_HEAD;
    public static final Block ALL_BLACK_CAT_WALL_HEAD;
    public static final Block BLACK_CAT_HEAD;
    public static final Block BLACK_CAT_WALL_HEAD;
    public static final Block BRITISH_SHORTHAIR_CAT_HEAD;
    public static final Block BRITISH_SHORTHAIR_CAT_WALL_HEAD;
    public static final Block CALICO_CAT_HEAD;
    public static final Block CALICO_CAT_WALL_HEAD;
    public static final Block JELLIE_CAT_HEAD;
    public static final Block JELLIE_CAT_WALL_HEAD;
    public static final Block PERSIAN_CAT_HEAD;
    public static final Block PERSIAN_CAT_WALL_HEAD;
    public static final Block RAGDOLL_CAT_HEAD;
    public static final Block RAGDOLL_CAT_WALL_HEAD;
    public static final Block RED_CAT_HEAD;
    public static final Block RED_CAT_WALL_HEAD;
    public static final Block SIAMESE_CAT_HEAD;
    public static final Block SIAMESE_CAT_WALL_HEAD;
    public static final Block TABBY_CAT_HEAD;
    public static final Block TABBY_CAT_WALL_HEAD;
    public static final Block WHITE_CAT_HEAD;
    public static final Block WHITE_CAT_WALL_HEAD;
    public static final Block ENDERMAN_HEAD;
    public static final Block ENDERMAN_WALL_HEAD;
    public static final Block FOX_HEAD;
    public static final Block FOX_WALL_HEAD;
    public static final Block SNOW_FOX_HEAD;
    public static final Block SNOW_FOX_WALL_HEAD;
    public static final Block IRON_GOLEM_HEAD;
    public static final Block IRON_GOLEM_WALL_HEAD;
    public static final Block AGGRESSIVE_PANDA_HEAD;
    public static final Block AGGRESSIVE_PANDA_WALL_HEAD;
    public static final Block BROWN_PANDA_HEAD;
    public static final Block BROWN_PANDA_WALL_HEAD;
    public static final Block LAZY_PANDA_HEAD;
    public static final Block LAZY_PANDA_WALL_HEAD;
    public static final Block PANDA_HEAD;
    public static final Block PANDA_WALL_HEAD;
    public static final Block PLAYFUL_PANDA_HEAD;
    public static final Block PLAYFUL_PANDA_WALL_HEAD;
    public static final Block WEAK_PANDA_HEAD;
    public static final Block WEAK_PANDA_WALL_HEAD;
    public static final Block WORRIED_PANDA_HEAD;
    public static final Block WORRIED_PANDA_WALL_HEAD;
    public static final Block DROWNED_HEAD;
    public static final Block DROWNED_WALL_HEAD;
    public static final Block RED_PARROT_HEAD;
    public static final Block RED_PARROT_WALL_HEAD;
    public static final Block GREEN_PARROT_HEAD;
    public static final Block GREEN_PARROT_WALL_HEAD;
    public static final Block BLUE_PARROT_HEAD;
    public static final Block BLUE_PARROT_WALL_HEAD;
    public static final Block CYAN_PARROT_HEAD;
    public static final Block CYAN_PARROT_WALL_HEAD;
    public static final Block GRAY_PARROT_HEAD;
    public static final Block GRAY_PARROT_WALL_HEAD;
    public static final Block STRAY_SKULL;
    public static final Block STRAY_WALL_SKULL;
    public static final Block SHULKER_HEAD;
    public static final Block SHULKER_WALL_HEAD;
    public static final Block HUSK_HEAD;
    public static final Block HUSK_WALL_HEAD;
    public static final Block PIG_HEAD;
    public static final Block PIG_WALL_HEAD;
    public static final Block SPIDER_HEAD;
    public static final Block SPIDER_WALL_HEAD;
    public static final Block CAVE_SPIDER_HEAD;
    public static final Block CAVE_SPIDER_WALL_HEAD;
    public static final Block BLAZE_HEAD;
    public static final Block BLAZE_WALL_HEAD;
    public static final Block BLACK_RABBIT_HEAD;
    public static final Block BLACK_RABBIT_WALL_HEAD;
    public static final Block BROWN_RABBIT_HEAD;
    public static final Block BROWN_RABBIT_WALL_HEAD;
    public static final Block EVIL_RABBIT_HEAD;
    public static final Block EVIL_RABBIT_WALL_HEAD;
    public static final Block GOLD_RABBIT_HEAD;
    public static final Block GOLD_RABBIT_WALL_HEAD;
    public static final Block SALT_RABBIT_HEAD;
    public static final Block SALT_RABBIT_WALL_HEAD;
    public static final Block WHITE_RABBIT_HEAD;
    public static final Block WHITE_RABBIT_WALL_HEAD;
    public static final Block WHITE_SPLOTCHED_RABBIT_HEAD;
    public static final Block WHITE_SPLOTCHED_RABBIT_WALL_HEAD;
    public static final Block TURTLE_HEAD;
    public static final Block TURTLE_WALL_HEAD;
    public static final Block WITHER_SKULL;
    public static final Block WITHER_WALL_SKULL;
    public static final Block WOLF_HEAD;
    public static final Block WOLF_WALL_HEAD;
    public static final Block BAT_HEAD;
    public static final Block BAT_WALL_HEAD;
    public static final Block WITCH_HEAD;
    public static final Block WITCH_WALL_HEAD;
    public static final Block CHICKEN_HEAD;
    public static final Block CHICKEN_WALL_HEAD;
    public static final Block PHANTOM_HEAD;
    public static final Block PHANTOM_WALL_HEAD;
    public static final Block SNOW_GOLEM_HEAD;
    public static final Block SNOW_GOLEM_WALL_HEAD;


    static {
        VILLAGER_HEAD = register("villager_head", new HeadedSkullBlock(HeadedSkullBlock.Type.VILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        VILLAGER_WALL_HEAD = register("villager_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.VILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(VILLAGER_HEAD)));
        EVOKER_HEAD = register("evoker_head", new HeadedSkullBlock(HeadedSkullBlock.Type.EVOKER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        EVOKER_WALL_HEAD = register("evoker_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.EVOKER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(EVOKER_HEAD)));
        VINDICATOR_HEAD = register("vindicator_head", new HeadedSkullBlock(HeadedSkullBlock.Type.VINDICATOR, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        VINDICATOR_WALL_HEAD = register("vindicator_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.VINDICATOR, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(VINDICATOR_HEAD)));
        PILLAGER_HEAD = register("pillager_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PILLAGER_WALL_HEAD = register("pillager_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PILLAGER_HEAD)));
        ZOMBIE_VILLAGER_HEAD = register("zombie_villager_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ZOMBIE_VILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ZOMBIE_VILLAGER_WALL_HEAD = register("zombie_villager_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ZOMBIE_VILLAGER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ZOMBIE_VILLAGER_HEAD)));
        WANDERING_TRADER_HEAD = register("wandering_trader_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WANDERING_TRADER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WANDERING_TRADER_WALL_HEAD = register("wandering_trader_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WANDERING_TRADER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WANDERING_TRADER_HEAD)));
        SHEEP_HEAD = register("sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        SHEEP_WALL_HEAD = register("sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(SHEEP_HEAD)));
        WHITE_SHEEP_HEAD = register("white_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WHITE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WHITE_SHEEP_WALL_HEAD = register("white_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WHITE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WHITE_SHEEP_HEAD)));
        ORANGE_SHEEP_HEAD = register("orange_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ORANGE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ORANGE_SHEEP_WALL_HEAD = register("orange_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ORANGE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ORANGE_SHEEP_HEAD)));
        MAGENTA_SHEEP_HEAD = register("magenta_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.MAGENTA_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        MAGENTA_SHEEP_WALL_HEAD = register("magenta_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.MAGENTA_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(MAGENTA_SHEEP_HEAD)));
        LIGHT_BLUE_SHEEP_HEAD = register("light_blue_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.LIGHT_BLUE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        LIGHT_BLUE_SHEEP_WALL_HEAD = register("light_blue_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.LIGHT_BLUE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(LIGHT_BLUE_SHEEP_HEAD)));
        YELLOW_SHEEP_HEAD = register("yellow_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.YELLOW_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        YELLOW_SHEEP_WALL_HEAD = register("yellow_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.YELLOW_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(YELLOW_SHEEP_HEAD)));
        LIME_SHEEP_HEAD = register("lime_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.LIME_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        LIME_SHEEP_WALL_HEAD = register("lime_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.LIME_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(LIME_SHEEP_HEAD)));
        PINK_SHEEP_HEAD = register("pink_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PINK_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PINK_SHEEP_WALL_HEAD = register("pink_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PINK_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PINK_SHEEP_HEAD)));
        GRAY_SHEEP_HEAD = register("gray_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.GRAY_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        GRAY_SHEEP_WALL_HEAD = register("gray_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.GRAY_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(GRAY_SHEEP_HEAD)));
        LIGHT_GRAY_SHEEP_HEAD = register("light_gray_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.LIGHT_GRAY_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        LIGHT_GRAY_SHEEP_WALL_HEAD = register("light_gray_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.LIGHT_GRAY_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(LIGHT_GRAY_SHEEP_HEAD)));
        CYAN_SHEEP_HEAD = register("cyan_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.CYAN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        CYAN_SHEEP_WALL_HEAD = register("cyan_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.CYAN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(CYAN_SHEEP_HEAD)));
        PURPLE_SHEEP_HEAD = register("purple_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PURPLE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PURPLE_SHEEP_WALL_HEAD = register("purple_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PURPLE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PURPLE_SHEEP_HEAD)));
        BLUE_SHEEP_HEAD = register("blue_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLUE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLUE_SHEEP_WALL_HEAD = register("blue_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLUE_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLUE_SHEEP_HEAD)));
        BROWN_SHEEP_HEAD = register("brown_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BROWN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BROWN_SHEEP_WALL_HEAD = register("brown_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BROWN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BROWN_SHEEP_HEAD)));
        GREEN_SHEEP_HEAD = register("green_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.GREEN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        GREEN_SHEEP_WALL_HEAD = register("green_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.GREEN_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(GREEN_SHEEP_HEAD)));
        RED_SHEEP_HEAD = register("red_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.RED_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        RED_SHEEP_WALL_HEAD = register("red_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.RED_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(RED_SHEEP_HEAD)));
        BLACK_SHEEP_HEAD = register("black_sheep_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLACK_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLACK_SHEEP_WALL_HEAD = register("black_sheep_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLACK_SHEEP, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLACK_SHEEP_HEAD)));
        ALLAY_HEAD = register("allay_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ALLAY, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).luminance(state -> 15)));
        ALLAY_WALL_HEAD = register("allay_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ALLAY, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).luminance(state -> 15).dropsLike(ALLAY_HEAD)));
        VEX_HEAD = register("vex_head", new HeadedSkullBlock(HeadedSkullBlock.Type.VEX, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        VEX_WALL_HEAD = register("vex_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.VEX, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(VEX_HEAD)));
        ILLUSIONER_HEAD = register("illusioner_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ILLUSIONER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ILLUSIONER_WALL_HEAD = register("illusioner_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ILLUSIONER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ILLUSIONER_HEAD)));
        PIGLIN_HEAD = register("piglin_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PIGLIN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PIGLIN_WALL_HEAD = register("piglin_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PIGLIN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PIGLIN_HEAD)));
        PIGLIN_BRUTE_HEAD = register("piglin_brute_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PIGLIN_BRUTE, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PIGLIN_BRUTE_WALL_HEAD = register("piglin_brute_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PIGLIN_BRUTE, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PIGLIN_BRUTE_HEAD)));
        ZOMBIFIED_PIGLIN_HEAD = register("zombified_piglin_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ZOMBIFIED_PIGLIN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ZOMBIFIED_PIGLIN_WALL_HEAD = register("zombified_piglin_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ZOMBIFIED_PIGLIN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ZOMBIFIED_PIGLIN_HEAD)));
        LEUCISTIC_AXOLOTL_HEAD = register("leucistic_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.LEUCISTIC_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        LEUCISTIC_AXOLOTL_WALL_HEAD = register("leucistic_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.LEUCISTIC_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(LEUCISTIC_AXOLOTL_HEAD)));
        BROWN_AXOLOTL_HEAD = register("brown_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BROWN_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BROWN_AXOLOTL_WALL_HEAD = register("brown_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BROWN_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BROWN_AXOLOTL_HEAD)));
        CYAN_AXOLOTL_HEAD = register("cyan_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.CYAN_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        CYAN_AXOLOTL_WALL_HEAD = register("cyan_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.CYAN_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(CYAN_AXOLOTL_HEAD)));
        GOLD_AXOLOTL_HEAD = register("gold_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.GOLD_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        GOLD_AXOLOTL_WALL_HEAD = register("gold_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.GOLD_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(GOLD_AXOLOTL_HEAD)));
        BLUE_AXOLOTL_HEAD = register("blue_axolotl_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLUE_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLUE_AXOLOTL_WALL_HEAD = register("blue_axolotl_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLUE_AXOLOTL, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLUE_AXOLOTL_HEAD)));
        COW_HEAD = register("cow_head", new HeadedSkullBlock(HeadedSkullBlock.Type.COW, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        COW_WALL_HEAD = register("cow_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.COW, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(COW_HEAD)));
        BROWN_MOOSHROOM_HEAD = register("brown_mooshroom_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BROWN_MOOSHROOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BROWN_MOOSHROOM_WALL_HEAD = register("brown_mooshroom_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BROWN_MOOSHROOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BROWN_MOOSHROOM_HEAD)));
        RED_MOOSHROOM_HEAD = register("red_mooshroom_head", new HeadedSkullBlock(HeadedSkullBlock.Type.RED_MOOSHROOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        RED_MOOSHROOM_WALL_HEAD = register("red_mooshroom_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.RED_MOOSHROOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(RED_MOOSHROOM_HEAD)));
        POLAR_BEAR_HEAD = register("polar_bear_head", new HeadedSkullBlock(HeadedSkullBlock.Type.POLAR_BEAR, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        POLAR_BEAR_WALL_HEAD = register("polar_bear_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.POLAR_BEAR, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(POLAR_BEAR_HEAD)));
        OCELOT_HEAD = register("ocelot_head", new HeadedSkullBlock(HeadedSkullBlock.Type.OCELOT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        OCELOT_WALL_HEAD = register("ocelot_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.OCELOT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(OCELOT_HEAD)));
        ALL_BLACK_CAT_HEAD = register("all_black_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ALL_BLACK_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ALL_BLACK_CAT_WALL_HEAD = register("all_black_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ALL_BLACK_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ALL_BLACK_CAT_HEAD)));
        BLACK_CAT_HEAD = register("black_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLACK_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLACK_CAT_WALL_HEAD = register("black_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLACK_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLACK_CAT_HEAD)));
        BRITISH_SHORTHAIR_CAT_HEAD = register("british_shorthair_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BRITISH_SHORTHAIR_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BRITISH_SHORTHAIR_CAT_WALL_HEAD = register("british_shorthair_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BRITISH_SHORTHAIR_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BRITISH_SHORTHAIR_CAT_HEAD)));
        CALICO_CAT_HEAD = register("calico_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.CALICO_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        CALICO_CAT_WALL_HEAD = register("calico_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.CALICO_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(CALICO_CAT_HEAD)));
        JELLIE_CAT_HEAD = register("jellie_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.JELLIE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        JELLIE_CAT_WALL_HEAD = register("jellie_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.JELLIE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(JELLIE_CAT_HEAD)));
        PERSIAN_CAT_HEAD = register("persian_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PERSIAN_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PERSIAN_CAT_WALL_HEAD = register("persian_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PERSIAN_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PERSIAN_CAT_HEAD)));
        RAGDOLL_CAT_HEAD = register("ragdoll_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.RAGDOLL_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        RAGDOLL_CAT_WALL_HEAD = register("ragdoll_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.RAGDOLL_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(RAGDOLL_CAT_HEAD)));
        RED_CAT_HEAD = register("red_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.RED_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        RED_CAT_WALL_HEAD = register("red_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.RED_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(RED_CAT_HEAD)));
        SIAMESE_CAT_HEAD = register("siamese_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.SIAMESE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        SIAMESE_CAT_WALL_HEAD = register("siamese_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.SIAMESE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(SIAMESE_CAT_HEAD)));
        TABBY_CAT_HEAD = register("tabby_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.TABBY_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        TABBY_CAT_WALL_HEAD = register("tabby_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.TABBY_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(TABBY_CAT_HEAD)));
        WHITE_CAT_HEAD = register("white_cat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WHITE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WHITE_CAT_WALL_HEAD = register("white_cat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WHITE_CAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WHITE_CAT_HEAD)));
        ENDERMAN_HEAD = register("enderman_head", new HeadedSkullBlock(HeadedSkullBlock.Type.ENDERMAN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        ENDERMAN_WALL_HEAD = register("enderman_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.ENDERMAN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(ENDERMAN_HEAD)));
        FOX_HEAD = register("fox_head", new HeadedSkullBlock(HeadedSkullBlock.Type.FOX, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        FOX_WALL_HEAD = register("fox_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.FOX, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(FOX_HEAD)));
        SNOW_FOX_HEAD = register("snow_fox_head", new HeadedSkullBlock(HeadedSkullBlock.Type.SNOW_FOX, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        SNOW_FOX_WALL_HEAD = register("snow_fox_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.SNOW_FOX, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(SNOW_FOX_HEAD)));
        IRON_GOLEM_HEAD = register("iron_golem_head", new HeadedSkullBlock(HeadedSkullBlock.Type.IRON_GOLEM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        IRON_GOLEM_WALL_HEAD = register("iron_golem_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.IRON_GOLEM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(IRON_GOLEM_HEAD)));
        AGGRESSIVE_PANDA_HEAD = register("aggressive_panda_head", new HeadedSkullBlock(HeadedSkullBlock.Type.AGGRESSIVE_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        AGGRESSIVE_PANDA_WALL_HEAD = register("aggressive_panda_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.AGGRESSIVE_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(AGGRESSIVE_PANDA_HEAD)));
        BROWN_PANDA_HEAD = register("brown_panda_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BROWN_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BROWN_PANDA_WALL_HEAD = register("brown_panda_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BROWN_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BROWN_PANDA_HEAD)));
        LAZY_PANDA_HEAD = register("lazy_panda_head", new HeadedSkullBlock(HeadedSkullBlock.Type.LAZY_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        LAZY_PANDA_WALL_HEAD = register("lazy_panda_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.LAZY_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(LAZY_PANDA_HEAD)));
        PANDA_HEAD = register("panda_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PANDA_WALL_HEAD = register("panda_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PANDA_HEAD)));
        PLAYFUL_PANDA_HEAD = register("playful_panda_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PLAYFUL_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PLAYFUL_PANDA_WALL_HEAD = register("playful_panda_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PLAYFUL_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PLAYFUL_PANDA_HEAD)));
        WEAK_PANDA_HEAD = register("weak_panda_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WEAK_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WEAK_PANDA_WALL_HEAD = register("weak_panda_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WEAK_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WEAK_PANDA_HEAD)));
        WORRIED_PANDA_HEAD = register("worried_panda_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WORRIED_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WORRIED_PANDA_WALL_HEAD = register("worried_panda_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WORRIED_PANDA, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WORRIED_PANDA_HEAD)));
        DROWNED_HEAD = register("drowned_head", new HeadedSkullBlock(HeadedSkullBlock.Type.DROWNED, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        DROWNED_WALL_HEAD = register("drowned_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.DROWNED, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(DROWNED_HEAD)));
        RED_PARROT_HEAD = register("red_parrot_head", new HeadedSkullBlock(HeadedSkullBlock.Type.RED_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        RED_PARROT_WALL_HEAD = register("red_parrot_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.RED_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(RED_PARROT_HEAD)));
        GREEN_PARROT_HEAD = register("green_parrot_head", new HeadedSkullBlock(HeadedSkullBlock.Type.GREEN_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        GREEN_PARROT_WALL_HEAD = register("green_parrot_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.GREEN_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(GREEN_PARROT_HEAD)));
        BLUE_PARROT_HEAD = register("blue_parrot_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLUE_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLUE_PARROT_WALL_HEAD = register("blue_parrot_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLUE_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLUE_PARROT_HEAD)));
        CYAN_PARROT_HEAD = register("cyan_parrot_head", new HeadedSkullBlock(HeadedSkullBlock.Type.CYAN_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        CYAN_PARROT_WALL_HEAD = register("cyan_parrot_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.CYAN_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(CYAN_PARROT_HEAD)));
        GRAY_PARROT_HEAD = register("gray_parrot_head", new HeadedSkullBlock(HeadedSkullBlock.Type.GRAY_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        GRAY_PARROT_WALL_HEAD = register("gray_parrot_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.GRAY_PARROT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(GRAY_PARROT_HEAD)));
        STRAY_SKULL = register("stray_skull", new HeadedSkullBlock(HeadedSkullBlock.Type.STRAY, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        STRAY_WALL_SKULL = register("stray_wall_skull", new HeadedWallSkullBlock(HeadedSkullBlock.Type.STRAY, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(STRAY_SKULL)));
        SHULKER_HEAD = register("shulker_head", new HeadedSkullBlock(HeadedSkullBlock.Type.SHULKER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        SHULKER_WALL_HEAD = register("shulker_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.SHULKER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(SHULKER_HEAD)));
        HUSK_HEAD = register("husk_head", new HeadedSkullBlock(HeadedSkullBlock.Type.HUSK, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        HUSK_WALL_HEAD = register("husk_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.HUSK, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(HUSK_HEAD)));
        PIG_HEAD = register("pig_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PIG, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PIG_WALL_HEAD = register("pig_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PIG, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PIG_HEAD)));
        SPIDER_HEAD = register("spider_head", new HeadedSkullBlock(HeadedSkullBlock.Type.SPIDER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        SPIDER_WALL_HEAD = register("spider_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.SPIDER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(SPIDER_HEAD)));
        CAVE_SPIDER_HEAD = register("cave_spider_head", new HeadedSkullBlock(HeadedSkullBlock.Type.CAVE_SPIDER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        CAVE_SPIDER_WALL_HEAD = register("cave_spider_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.CAVE_SPIDER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(CAVE_SPIDER_HEAD)));
        BLAZE_HEAD = register("blaze_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLAZE, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).luminance(state -> 15)));
        BLAZE_WALL_HEAD = register("blaze_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLAZE, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).luminance(state -> 15).dropsLike(BLAZE_HEAD)));
        BLACK_RABBIT_HEAD = register("black_rabbit_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BLACK_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BLACK_RABBIT_WALL_HEAD = register("black_rabbit_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BLACK_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BLACK_RABBIT_HEAD)));
        BROWN_RABBIT_HEAD = register("brown_rabbit_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BROWN_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BROWN_RABBIT_WALL_HEAD = register("brown_rabbit_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BROWN_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BROWN_RABBIT_HEAD)));
        EVIL_RABBIT_HEAD = register("the_killer_bunny_head", new HeadedSkullBlock(HeadedSkullBlock.Type.EVIL_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        EVIL_RABBIT_WALL_HEAD = register("the_killer_bunny_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.EVIL_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(EVIL_RABBIT_HEAD)));
        GOLD_RABBIT_HEAD = register("gold_rabbit_head", new HeadedSkullBlock(HeadedSkullBlock.Type.GOLD_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        GOLD_RABBIT_WALL_HEAD = register("gold_rabbit_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.GOLD_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(GOLD_RABBIT_HEAD)));
        SALT_RABBIT_HEAD = register("salt_rabbit_head", new HeadedSkullBlock(HeadedSkullBlock.Type.SALT_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        SALT_RABBIT_WALL_HEAD = register("salt_rabbit_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.SALT_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(SALT_RABBIT_HEAD)));
        WHITE_RABBIT_HEAD = register("white_rabbit_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WHITE_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WHITE_RABBIT_WALL_HEAD = register("white_rabbit_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WHITE_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WHITE_RABBIT_HEAD)));
        WHITE_SPLOTCHED_RABBIT_HEAD = register("white_splotched_rabbit_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WHITE_SPLOTCHED_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WHITE_SPLOTCHED_RABBIT_WALL_HEAD = register("white_splotched_rabbit_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WHITE_SPLOTCHED_RABBIT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WHITE_SPLOTCHED_RABBIT_HEAD)));
        TURTLE_HEAD = register("turtle_head", new HeadedSkullBlock(HeadedSkullBlock.Type.TURTLE, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        TURTLE_WALL_HEAD = register("turtle_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.TURTLE, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(TURTLE_HEAD)));
        WITHER_SKULL = register("wither_skull", new HeadedSkullBlock(HeadedSkullBlock.Type.WITHER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WITHER_WALL_SKULL = register("wither_wall_skull", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WITHER, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WITHER_SKULL)));
        WOLF_HEAD = register("wolf_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WOLF, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WOLF_WALL_HEAD = register("wolf_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WOLF, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WOLF_HEAD)));
        BAT_HEAD = register("bat_head", new HeadedSkullBlock(HeadedSkullBlock.Type.BAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        BAT_WALL_HEAD = register("bat_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.BAT, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(BAT_HEAD)));
        WITCH_HEAD = register("witch_head", new HeadedSkullBlock(HeadedSkullBlock.Type.WITCH, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        WITCH_WALL_HEAD = register("witch_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.WITCH, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(WITCH_HEAD)));
        CHICKEN_HEAD = register("chicken_head", new HeadedSkullBlock(HeadedSkullBlock.Type.CHICKEN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        CHICKEN_WALL_HEAD = register("chicken_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.CHICKEN, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(CHICKEN_HEAD)));
        PHANTOM_HEAD = register("phantom_head", new HeadedSkullBlock(HeadedSkullBlock.Type.PHANTOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        PHANTOM_WALL_HEAD = register("phantom_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.PHANTOM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(PHANTOM_HEAD)));
        SNOW_GOLEM_HEAD = register("snow_golem_head", new HeadedSkullBlock(HeadedSkullBlock.Type.SNOW_GOLEM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F)));
        SNOW_GOLEM_WALL_HEAD = register("snow_golem_wall_head", new HeadedWallSkullBlock(HeadedSkullBlock.Type.SNOW_GOLEM, AbstractBlock.Settings.of(Material.DECORATION).strength(1.0F).dropsLike(SNOW_GOLEM_HEAD)));
    }

    private static Block register(String name, Block block) {
        return Registry.register(Registry.BLOCK, new Identifier(Headed.MOD_ID, name), block);
    }

    public static void registerModBlocks() {
        Headed.LOGGER.debug("Registering Headed blocks");
    }
}
